### ISSUE TITLE
Roadmap HackMiami Con 7 💪

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/batimagen#27]
### Pendiente

**Previas**
- [x] Revisar diseño y funcionalidades @ElenaMLopez @FranciscoValdesoiro 
- [x] Revisar las ramas secundarias por si algo no estuviera en `development` @ElenaMLopez @FranciscoValdesoiro 
- [ ] Revisar los issues pendientes
   - [x] #24 Security @UlisesGascon 
   - [ ] #21 Gestionar Forense @ElenaMLopez @FranciscoValdesoiro 
- [x] Frontend Revisar todo @ElenaMLopez @FranciscoValdesoiro 
    - [ ] #16 Vista resultados

**Código**
- [x] #25 Dockerizar la APP
   - [x] Generar un `dockerfile` con todas las dependencias sobre un Ubuntu. @FranciscoValdesoiro @ElenaMLopez 
   - [x] Quitar los scripts `sh` del aplicativo. @UlisesGascon 
- [x] Refactorizar el Backend
   - [x] Estabilizar el código y los procesos hijo @UlisesGascon 
   - [x] #18 Quitar el Honeypot mode @UlisesGascon 
   - [x] Hacer dependencias de terceros opcional (modo offline) (Virustotal, Google, etc...) @UlisesGascon @ElenaMLopez @FranciscoValdesoiro 

**Opcional**
- [ ] Re-diseño y trabajo con Ancoar
- [ ] Testing :trollface: 

**Documentación**
- [ ] Guía de instalación paso a paso [EN/ES] @ElenaMLopez @FranciscoValdesoiro 
- [ ] Vídeo de Youtube sobre la instalación @ElenaMLopez @FranciscoValdesoiro 
- [ ] Vídeo demo de Youtube @ElenaMLopez @FranciscoValdesoiro 

### Notas
- Trabajamos en la rama `development`
- [Apuntes de Docker](https://julianduque.co/nev-docker/)

### Roadmap
- 0.2.0 con Docker (crítico) Deadline `Semana 12'19` (Docker + Previo)
- 1.0.0 con todo lo demás (menos crítico) `Semana 14'19` (Código)
- Semana Santa documentación, Slides, etc...

### Nombre de las releases
- [Pintoras del mundo!](https://www.publico.es/sociedad/admiralas-10-pintoras-puedes-dejar.html)

**Comment by UlisesGascon** [comment]
Decidido! La release `1.0.0` será un homenaje a la pintora mexicana Frida Kalho. 

![Imagen de Frida Kalho en la película COCO](https://vignette.wikia.nocookie.net/disneyypixar/images/1/12/Frida_1.jpg/revision/latest?cb=20180628031759&path-prefix=es)

**Comment by UlisesGascon** [comment]
Gran trabajo en miami @ElenaMLopez y @FranciscoValdesoiro !! :muscle:
