### ISSUE TITLE
RoadMap for Next Release

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/batimagen#43]
### Changes requested
- [ ] Upgrade dependencies
- [ ] Convert `./lib/phoenix.js` internal module to external dependency in NPM
- [ ] Let's add testing with Jest, btw!
- [ ] Add Stego analysis feature. _Leader: @FranciscoValdesoiro_
- [ ] Define new architecture for Backend to support large files (database and better HTTP Handler, API endpoints)
- [ ] Migration from Jade to Ejs (TBC with frontend architecture). _Leader: @KoolTheba_
- [ ] New frontend architecture? Based on new Backend features such as Api Rest
- [ ] New Frontend Redesign Brainstorming. _Related: #16 _
- [ ] Reports generation as PDF? Zip folder?
- [ ] Release name: _Georgia O'Keeffe_?

### Legacy pending
- [ ] Forensic Paper Dependency #21
- [ ] :warning: WS-2019-0047 Medium Severity Vulnerability detected by WhiteSource #30
- [ ] :warning: CVE-2017-18214 High Severity Vulnerability detected by WhiteSource #24
- [ ] :warning: remove old branches from this project. _leader: @UlisesGascon_ 

### Documentation
- [ ] Installation guide [EN/ES]
- [ ] Youtube videos about Batimagen
- [ ] Full demo video 

### Bugs to fix
- [ ] Missing back button
